-- GROUP BY : 여러 개의 값을 묶어서 그룹 기준 제시
SELECT DEPT_CODE, SUM(SALARY)
FROM EMPLOYEE;

-- 각 부서 별 급여 합계 조회
SELECT DEPT_CODE, SUM(SALARY)
FROM EMPLOYEE
GROUP BY DEPT_CODE;

--EMPLOYEE테이블에서 부서 코드 별 그룹을 지정하여
--부서코드, 그룹 별 급여 합계, 그룹별 급여 평균, 인원 수 조회
SELECT DEPT_CODE, SUM(SALARY), AVG(SALARY), COUNT(*)
FROM EMPLOYEE
GROUP BY DEPT_CODE;

--EMPLOYEE테이블에서 부서코드와 보너스 받는 사원 수 조회
SELECT DEPT_CODE, COUNT(BONUS)
FROM EMPLOYEE
GROUP BY DEPT_CODE;

--EMPLOYEE테이블에서 성별과 성별 별 급여 평균, 급여 합계, 인원 수 조회
SELECT CASE WHEN SUBSTR(EMP_NO, INSTR(EMP_NO, '-')+1, 1) = 1 THEN '남'
        ELSE '여'
        END 성별,
        AVG(SALARY), SUM(SALARY), COUNT(*)
FROM EMPLOYEE
GROUP BY CASE WHEN SUBSTR(EMP_NO, INSTR(EMP_NO, '-')+1, 1) = 1 THEN '남'
         ELSE '여'
         END;

SELECT DECODE(SUBSTR(EMP_NO, INSTR(EMP_NO, '-')+1, 1), '1', '남', '여') 성별,
        AVG(SALARY), SUM(SALARY), COUNT(*)
FROM EMPLOYEE
--GROUP BY DECODE(SUBSTR(EMP_NO, INSTR(EMP_NO, '-')+1, 1), '1', '남', '여');
GROUP BY SUBSTR(EMP_NO, INSTR(EMP_NO, '-')+1, 1);

--EMPLOYEE테이블에서 부서코드 별로 같은 직급인 사원의 급여 합계 조회
SELECT DEPT_CODE, JOB_CODE, SUM(SALARY)
FROM EMPLOYEE
GROUP BY DEPT_CODE, JOB_CODE;

--HAVING : 그룹함수에 대한 조건 설정
--부서코드와 급여 300만 이상인 직원의 그룹 별 평균 급여 조회
SELECT DEPT_CODE, AVG(SALARY)
FROM EMPLOYEE
WHERE SALARY >= 3000000
GROUP BY DEPT_CODE;

--부서코드와 급여 평균이 300만 이상인 그룹 조회
SELECT DEPT_CODE, AVG(SALARY)
FROM EMPLOYEE
GROUP BY DEPT_CODE
HAVING AVG(SALARY) >= 3000000;

-- 부서 별 그룹의 급여 합계 중 9백만원을 초과하는 부서 코드와 급여 합계 조회
SELECT DEPT_CODE, SUM(SALARY)
FROM EMPLOYEE
GROUP BY DEPT_CODE
HAVING SUM(SALARY) > 9000000;

/*
SELECT문, 6개의 절 구성
5    SELECT      조회할 컬럼
1    FROM        참조할 테이블 명
2    WHERE       일반 컬럼 조건식
3    GROUP BY    그룹함수에 적용할 그룹 기준
4    HAVING      그룹함수 조건식
6    ORDER BY    정렬 기준
*/
--                    (생략가능)오름차순,내림차순
--ORDER BY 컬럼명|컬럼별칭|컬럼순번 [ASC]|DESC [NULLS FIRST|LAST]
SELECT EMP_ID, EMP_NAME, SALARY 급여, DEPT_CODE
FROM EMPLOYEE
--ORDER BY EMP_NAME -- 기본은 이름 오름차순
--ORDER BY EMP_NAME ASC; -- 이름 오름차순
--ORDER BY EMP_NAME DESC; -- 이름 내림차순
--ORDER BY 급여 DESC; -- 급여 내림차순
--ORDER BY 4; --추천 X SELECT에 적은 순서
--ORDER BY DEPT_CODE DESC NULLS LAST; --기본은 오름차순은 NULL이 마지막,내림차순은 NULL 처음
ORDER BY DEPT_CODE, EMP_NAME;

-- 집합 연산자 : 여러 가지 조건이 있을 때 그에 해당하는 여러 개의 결과 값을 결합하고 싶을 때
-- UNION = 합집합(OR)
SELECT EMP_ID, EMP_NAME FROM EMPLOYEE
--WHERE EMP_ID = 200 OR EMP_ID = 201;
WHERE EMP_ID IN (200, 201);

SELECT EMP_ID, EMP_NAME
FROM EMPLOYEE
WHERE EMP_ID = 200
UNION
SELECT EMP_ID, EMP_NAME
FROM EMPLOYEE
WHERE EMP_ID = 201;

SELECT EMP_NAME --위에 있는 거 기준 컬럼명, 개수 같고 타입이 같아야 유니온 쓸 수 있음
FROM EMPLOYEE
WHERE EMP_ID = 200
UNION
SELECT DEPT_TITLE
FROM DEPARTMENT
WHERE DEPT_ID = 'D9';

-- UNION ALL = 합집합 + 교집합
-- INTERSECT = 교집합(AND)
-- MINUS = 차집합
SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
INTERSECT -- AND
SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE SALARY > 3000000;

SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
UNION ALL -- 중복 되는거 두 번 나옴 EX)심봉선, 대북혼 (교집합)
SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE SALARY > 3000000;

SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
MINUS
SELECT EMP_ID, EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE SALARY > 3000000;









