--JOIN : 하나 이상의 테이블에서 데이터를 조회하기 위해 사용
--테이블 연결은 "같은 데이터" 값으로

--사번, 사원 명, 부서코드, 부서 명 조회
--사번, 사원 명, 부서코드 => EMPLOYEE(EMP_ID, EMP_NAME, DEPT_CODE)
--부서코드, 부서 명 => DEPARTMENT(DEPT_ID, DEPT_TITLE)
SELECT EMP_ID, EMP_NAME, DEPT_CODE
FROM EMPLOYEE;
SELECT DEPT_ID, DEPT_TITLE
FROM DEPARTMENT;
--DEPT_CODE에 들어가 있는 값과 DEPT_ID에 들어가 있는 값이 같으므로 서로 연결(JOIN) 가능

--내부 조인(INNER JOIN) : 오라클 구문, ANSI 표준 구문
--오라클 구문 : FROM절에 모든 테이블 명 기술, WHERE절에 합치기에 사용할 컬럼 명시
--사번, 사원 명, 부서코드, 부서 명 조회
SELECT EMP_ID, EMP_NAME, DEPT_CODE, DEPT_TITLE
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_CODE = DEPT_ID;

--사번, 사원 명, 직급코드, 직급 명 조회
SELECT EMP_ID, EMP_NAME, JOB.JOB_CODE, JOB_NAME
FROM EMPLOYEE, JOB
WHERE EMPLOYEE.JOB_CODE = JOB.JOB_CODE;

SELECT EMP_ID, EMP_NAME, E.JOB_CODE, JOB_NAME
FROM EMPLOYEE E, JOB J
WHERE E.JOB_CODE = J.JOB_CODE;

--ANSI 표준 구문 : FROM절에 연결할 테이블 명 JOIN으로 연결
--                  컬럼 명에 따라 ON/USING 사용
--사번, 사원 명, 부서코드, 부서 명 조회
SELECT EMP_ID, EMP_NAME, DEPT_CODE, DEPT_TITLE
FROM EMPLOYEE
     JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID); -- ON : 컬러명 다르면

--사번, 사원 명, 직급코드, 직급 명 조회
SELECT EMP_ID, EMP_NAME, JOB_CODE, JOB_NAME
FROM EMPLOYEE
     JOIN JOB USING(JOB_CODE); -- USING : 컬럼명 같으면

SELECT EMP_ID, EMP_NAME, E.JOB_CODE, JOB_NAME
FROM EMPLOYEE E
     JOIN JOB J ON(E.JOB_CODE = J.JOB_CODE);

-- 부서 명과 해당 부서의 지역 명 조회
-- 오라클
SELECT DEPT_TITLE, LOCAL_NAME
FROM DEPARTMENT , LOCATION 
WHERE LOCATION_ID = LOCAL_CODE;
--ANSI
SELECT DEPT_TITLE, LOCAL_NAME
FROM DEPARTMENT
     JOIN LOCATION ON(LOCATION_ID = LOCAL_CODE);
     
--외부 조인(OUTER JOIN) : 컬럼 값이 일치하지 않는 행도 조인에 포함
--LEFT [OUTER] JOIN : 합치기에 사용한 두 테이블 중 왼편에 기술된 테이블의 행을 기준으로 JOIN
--사원 명, 부서 명 조회
--ANSI
SELECT EMP_NAME, DEPT_TITLE
FROM EMPLOYEE
     LEFT OUTER JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID);
--오라클 : 기준이 아닌 테이블의 컬럼에 (+) 붙이기
SELECT EMP_NAME, DEPT_TITLE
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_CODE = DEPT_ID(+);

--RIGHT [OUTER] JOIN : 합치기에 사용한 두 테이블 중 오른편에 기술된 테이블의 행을 기준으로 JOIN
--ANSI
SELECT EMP_NAME, DEPT_TITLE
FROM EMPLOYEE
     RIGHT JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID);
--오라클
SELECT EMP_NAME, DEPT_TITLE
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_CODE(+) = DEPT_ID;

--FULL [OUTER] JOIN : 합치기에 사용한 두 테이블 모두를 기준으로 JOIN
--ANSI
SELECT EMP_NAME, DEPT_TITLE
FROM EMPLOYEE
     FULL OUTER JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID);

--오라클 : FULL OUTER JOIN 구현 불가
SELECT EMP_NAME, DEPT_TITLE
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_CODE(+) = DEPT_ID(+);

--다중 조인
-- 사번, 사원 명, 부서코드, 부서명, 근무지역명
--오라클 : 순서 상관 X
SELECT EMP_ID, EMP_NAME, DEPT_CODE, DEPT_TITLE, LOCAL_NAME
FROM EMPLOYEE, DEPARTMENT, LOCATION
WHERE DEPT_CODE = DEPT_ID 
      AND LOCATION_ID = LOCAL_CODE;
--ANSI : 순서가 중요함!!! (연결 가능한 지 고려)
SELECT EMP_ID, EMP_NAME, DEPT_ID, DEPT_TITLE, LOCAL_NAME
FROM EMPLOYEE --EMPLOYEE와 LOCATION은 연결할 수 없음
     JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
     JOIN LOCATION ON(LOCATION_ID = LOCAL_CODE);

--직급이 대리이면서 아시아 지역에 근무하는 직원의 사번, 이름, 직급명, 부서명, 근무 지역명, 급여 조회
--오라클
SELECT EMP_ID, EMP_NAME, JOB_NAME, DEPT_TITLE, LOCAL_NAME, SALARY
FROM EMPLOYEE E, JOB J, DEPARTMENT D, LOCATION
WHERE E.JOB_CODE = J.JOB_CODE 
      AND DEPT_ID = DEPT_CODE 
      AND LOCAL_CODE = LOCATION_ID 
      AND JOB_NAME = '대리'
      AND LOCAL_NAME LIKE 'ASIA%';
--ANSI
SELECT EMP_ID, EMP_NAME, JOB_NAME, DEPT_TITLE, LOCAL_NAME, SALARY
FROM EMPLOYEE
     JOIN JOB USING(JOB_CODE)
     JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
     JOIN LOCATION ON(LOCATION_ID = LOCAL_CODE)
WHERE JOB_NAME = '대리'
      AND LOCAL_NAME LIKE 'ASIA%';



















